use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Collections::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Collections::Id)
                            .integer()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Collections::Label).string().not_null())
                    .col(ColumnDef::new(Collections::Key).string().not_null())
                    .col(ColumnDef::new(Collections::Description).string())
                    .col(
                        ColumnDef::new(Collections::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Collections::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Texts::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Texts::Id)
                            .integer()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Texts::Content).string().not_null())
                    .col(ColumnDef::new(Texts::Kind).string().not_null())
                    .col(
                        ColumnDef::new(Texts::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Files::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Files::Id)
                            .integer()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Files::FileUuid).string())
                    .col(ColumnDef::new(Files::StoragePath).string().not_null())
                    .col(ColumnDef::new(Files::OriginalFilename).string().not_null())
                    .col(ColumnDef::new(Files::MimeType).string())
                    .col(ColumnDef::new(Files::ByteSize).integer())
                    .col(ColumnDef::new(Files::Sha256).string())
                    .col(
                        ColumnDef::new(Files::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Tags::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Tags::Id)
                            .integer()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Tags::Name).string().not_null())
                    .col(
                        ColumnDef::new(Tags::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Snippets::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Snippets::Id)
                            .integer()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Snippets::ConnectionId).integer().not_null())
                    .col(ColumnDef::new(Snippets::Title).string().not_null())
                    .col(ColumnDef::new(Snippets::Description).string())
                    .col(ColumnDef::new(Snippets::CurrentHistoryId).integer())
                    .col(
                        ColumnDef::new(Snippets::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Snippets::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_snippets_connection_id")
                            .from(Snippets::Table, Snippets::ConnectionId)
                            .to(Collections::Table, Collections::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_snippets_current_history_id")
                            .from(Snippets::Table, Snippets::CurrentHistoryId)
                            .to(Histories::Table, Histories::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Nodes::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Nodes::Id)
                            .integer()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Nodes::Kind).string().not_null())
                    .col(ColumnDef::new(Nodes::SnippetId).integer().not_null())
                    .col(ColumnDef::new(Nodes::TextId).integer())
                    .col(ColumnDef::new(Nodes::FileId).integer())
                    .col(ColumnDef::new(Nodes::MetaJson).string())
                    .col(
                        ColumnDef::new(Nodes::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_nodes_snippet_id")
                            .from(Nodes::Table, Nodes::SnippetId)
                            .to(Snippets::Table, Snippets::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_nodes_text_id")
                            .from(Nodes::Table, Nodes::TextId)
                            .to(Texts::Table, Texts::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_nodes_file_id")
                            .from(Nodes::Table, Nodes::FileId)
                            .to(Files::Table, Files::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(Histories::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Histories::Id)
                            .integer()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Histories::SnippetId).integer().not_null())
                    .col(
                        ColumnDef::new(Histories::VersionNumber)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Histories::Message).string())
                    .col(
                        ColumnDef::new(Histories::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Histories::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_histories_snippet_id")
                            .from(Histories::Table, Histories::SnippetId)
                            .to(Snippets::Table, Snippets::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(HistoryNodes::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(HistoryNodes::HistoryId).integer().not_null())
                    .col(ColumnDef::new(HistoryNodes::NodeId).integer().not_null())
                    .col(
                        ColumnDef::new(HistoryNodes::OrderIndex)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(HistoryNodes::AliasName).string())
                    .col(
                        ColumnDef::new(HistoryNodes::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .name("pk_history_nodes")
                            .col(HistoryNodes::HistoryId)
                            .col(HistoryNodes::NodeId),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_history_nodes_history_id")
                            .from(HistoryNodes::Table, HistoryNodes::HistoryId)
                            .to(Histories::Table, Histories::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_history_nodes_node_id")
                            .from(HistoryNodes::Table, HistoryNodes::NodeId)
                            .to(Nodes::Table, Nodes::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(SnippetTags::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(SnippetTags::SnippetId).integer().not_null())
                    .col(ColumnDef::new(SnippetTags::TagId).integer().not_null())
                    .col(
                        ColumnDef::new(SnippetTags::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .name("pk_snippet_tags")
                            .col(SnippetTags::SnippetId)
                            .col(SnippetTags::TagId),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_snippet_tags_snippet_id")
                            .from(SnippetTags::Table, SnippetTags::SnippetId)
                            .to(Snippets::Table, Snippets::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_snippet_tags_tag_id")
                            .from(SnippetTags::Table, SnippetTags::TagId)
                            .to(Tags::Table, Tags::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_collections_label")
                    .table(Collections::Table)
                    .col(Collections::Label)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_collections_key")
                    .table(Collections::Table)
                    .col(Collections::Key)
                    .unique()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_collections_created_at")
                    .table(Collections::Table)
                    .col(Collections::CreatedAt)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_texts_kind")
                    .table(Texts::Table)
                    .col(Texts::Kind)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_files_file_uuid")
                    .table(Files::Table)
                    .col(Files::FileUuid)
                    .unique()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_files_sha256")
                    .table(Files::Table)
                    .col(Files::Sha256)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_snippets_connection_id")
                    .table(Snippets::Table)
                    .col(Snippets::ConnectionId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_snippets_current_history_id")
                    .table(Snippets::Table)
                    .col(Snippets::CurrentHistoryId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_snippets_updated_at")
                    .table(Snippets::Table)
                    .col(Snippets::UpdatedAt)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_nodes_kind")
                    .table(Nodes::Table)
                    .col(Nodes::Kind)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_nodes_text_id")
                    .table(Nodes::Table)
                    .col(Nodes::TextId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_nodes_file_id")
                    .table(Nodes::Table)
                    .col(Nodes::FileId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_nodes_snippet_id")
                    .table(Nodes::Table)
                    .col(Nodes::SnippetId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_histories_snippet_id")
                    .table(Histories::Table)
                    .col(Histories::SnippetId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_histories_created_at")
                    .table(Histories::Table)
                    .col(Histories::CreatedAt)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_history_nodes_node_id")
                    .table(HistoryNodes::Table)
                    .col(HistoryNodes::NodeId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_history_nodes_history_id")
                    .table(HistoryNodes::Table)
                    .col(HistoryNodes::HistoryId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_history_nodes_order")
                    .table(HistoryNodes::Table)
                    .col(HistoryNodes::HistoryId)
                    .col(HistoryNodes::OrderIndex)
                    .unique()
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(SnippetTags::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(HistoryNodes::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Histories::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Nodes::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Snippets::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Tags::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Files::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Texts::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(Collections::Table).to_owned())
            .await?;
        Ok(())
    }
}

#[derive(DeriveIden)]
enum Collections {
    Table,
    Id,
    Label,
    Key,
    Description,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum Texts {
    Table,
    Id,
    Content,
    Kind,
    CreatedAt,
}

#[derive(DeriveIden)]
enum Files {
    Table,
    Id,
    FileUuid,
    StoragePath,
    OriginalFilename,
    MimeType,
    ByteSize,
    Sha256,
    CreatedAt,
}

#[derive(DeriveIden)]
enum Tags {
    Table,
    Id,
    Name,
    CreatedAt,
}

#[derive(DeriveIden)]
enum Nodes {
    Table,
    Id,
    Kind,
    SnippetId,
    TextId,
    FileId,
    MetaJson,
    CreatedAt,
}

#[derive(DeriveIden)]
enum Snippets {
    Table,
    Id,
    ConnectionId,
    Title,
    Description,
    CurrentHistoryId,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum Histories {
    Table,
    Id,
    SnippetId,
    VersionNumber,
    Message,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum HistoryNodes {
    Table,
    HistoryId,
    NodeId,
    OrderIndex,
    AliasName,
    CreatedAt,
}

#[derive(DeriveIden)]
enum SnippetTags {
    Table,
    SnippetId,
    TagId,
    CreatedAt,
}
